# Generated by Django 5.2.6 on 2025-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Completed Project',
                'verbose_name_plural': 'Completed Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Live Project',
                'verbose_name_plural': 'Live Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project (Legacy)', 'verbose_name_plural': 'Projects (Legacy)'},
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
