# Generated by Django 5.2.1 on 2025-10-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_completedproject_liveproject_alter_project_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedProject',
        ),
        migrations.DeleteModel(
            name='LiveProject',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='work',
            field=models.TextField(blank=True, help_text='Type of work performed', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project image', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project name (will be shown in bold)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.CharField(help_text='Project quantity', max_length=100),
        ),
    ]
