# Generated by Django 5.2.1 on 2025-10-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='work',
        ),
    ]
