# Generated by Django 5.2.1 on 2025-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='work',
            field=models.TextField(blank=True, help_text='Type of work performed', null=True),
        ),
    ]
