# Generated by Django 4.2.5 on 2025-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigiousProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('details', models.TextField(help_text='Project description')),
                ('quantity', models.CharField(blank=True, help_text='Project quantity/scale', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Project location', max_length=200)),
                ('client', models.CharField(blank=True, help_text='Client name', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Project image', null=True, upload_to='prestigious_projects/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestigious Project',
                'verbose_name_plural': 'Prestigious Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
