# Generated by Django 5.2.6 on 2025-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestigious_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestigiousproject',
            name='work_details',
            field=models.TextField(blank=True, help_text='Specific work details for the project'),
        ),
    ]
